/** Map route path → required read permission (for PermissionGate). Fallback when the nav API is unavailable. */
export const ROUTE_PERMISSIONS: Record<string, string> = {
  '/dashboard': 'system:read',
  '/users': 'user:read',
  '/roles': 'permission:read',
  '/accounts': 'account:read',
  '/rules': 'rule:read',
  '/fans': 'member:read',
  '/payments': 'payment:read',
  '/modules': 'module:read',
  '/settings': 'setting:read',
  '/cloud': 'cloud:read',
  '/logs': 'message:read',
  '/materials': 'material:read',
  '/points': 'points:read',
  '/menu': 'menu:read',
  '/checkin': 'checkin:read',
  '/lucky-draw': 'lucky_draw:read',
  '/coupons': 'coupon:read',
  '/votes': 'vote:read',
  '/seckills': 'seckill:read',
  '/member-cards': 'member_card:read',
  '/shop/admin': 'shop:write',
  '/shop/orders': 'shop:read',
  '/shop': 'shop:read',
  '/distributions': 'distribution:read',
  '/ai-admin': 'ai:read',
  '/audit-logs': 'audit:read',
  '/mail-templates': 'mail_template:read',
  '/tasks': 'task:read',
  '/tenants': 'tenant:read',
  '/member-card': 'member_card:read',
  '/ai-chat': 'ai:read',
  '/files': 'user:read',
};
