export const ROUTE_PATH = {
  root: '/',
  index: '/users',
  signIn: '/signin',
  signUp: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  users: '/users',
  accounts: '/accounts',
  rules: '/rules',
  fans: '/fans',
  payments: '/payments',
  modules: '/modules',
  cloud: '/cloud',
  logs: '/message-logs',
  materials: '/materials',
  profile: '/profile',
  tasks: '/tasks',
  files: '/files',
  tenants: '/tenants',
  dashboard: '/dashboard',
  auditLogs: '/audit-logs',
  mailTemplates: '/mail-templates',
  aiChat: '/ai/chat',
  aiAdmin: '/ai/admin',
  notFound: '/404',
} as const;
